name: Deploy Blog

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 必须设置为 0，否则 git log 拿不到准确日期

      # 1. 安装 pnpm (这是必须的，否则后面的命令会报错)
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # 或者写 latest

      # 2. 设置 Node 环境，并开启 pnpm 缓存
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 3. 安装依赖 (使用 pnpm)
      - name: Install dependencies
        run: pnpm install

      - name: Generate List and Fix Dates
        run: npm run gen

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: auto fix md dates and update blogList" || echo "No changes to commit"
          git push

      # 4. 构建项目
      - name: Build Project
        # 这里会运行 pnpm run build，内部应包含 node generateBlogList.js
        run: pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4